/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectcafe;

import Class.Product;
import Class.User;
import ConnectDb.dbconnect;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class MainForm extends javax.swing.JFrame {

    dbconnect db = new dbconnect();
    Connection conn = db.connect();
    User user;

    public MainForm(User u) {
        this.user = u;
        initComponents();
        ShowBan();
        Jmenu.setText(u.getName());
        PanelOder.setVisible(false);
    }

    public void getOrder(Integer TableID) {
        ResultSet result = null;
        String sql = "SELECT IDOrder FROM orderr where TableID =" + TableID + " AND Status = 0 ";
        try {
            Statement statement = conn.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while (rs.next()) {
                lbOrderID.setText(rs.getString("IDOrder"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Đã xảy ra lỗi");
        }
    }

    public static void ShowOrderTotable(JTable tbl, ResultSet rs) {
        try {
            DefaultTableModel model = (DefaultTableModel) tbl.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                String rows[] = new String[3];
                rows[0] = rs.getString("ProductName");
                rows[1] = rs.getString("Amount");
                rows[2] = rs.getString("Price");
                model.addRow(rows);
            }
        } catch (SQLException ex) {

        }
    }

    public void UpdateStatus(String TableId) {
        getOrder(Integer.parseInt(TableId));
        ShowOrderTotable(tblOrder, db.getOrderDetails(Integer.parseInt(lbOrderID.getText())));
        btnOpen.setVisible(false);
        lbStatus.setText("Có người");
        pnID.setVisible(true);
        btnHuy.setEnabled(false);
        lbStatus.setVisible(true);
        lbTongTien.setText(String.valueOf(db.getTotalMoney(db.getOrderDetails(Integer.parseInt(lbOrderID.getText()))))+" VND");  
    }

    public void ShowBan() {
        try {
            ResultSet rs = db.getTable();
            while (rs.next()) {
                JButton btn = new JButton();
                btn.setText(rs.getString("Name"));
                btn.setName(rs.getString("TableID"));
                btn.setPreferredSize(new Dimension(103, 60));
                btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Household-Table-icon.png")));
                if (rs.getString("Status").equals("Trống")) {
                    btn.setBackground(Color.WHITE);
                } else {
                    btn.setBackground(Color.RED);
                }
                JPBan.add(btn);
                btn.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        PanelOder.setVisible(true);
                        LbTenBan.setText(btn.getText());
                        btnOpen.setName(btn.getName());
                        if (btn.getBackground().equals(Color.RED)) {
                            UpdateStatus(btn.getName());
                        } else {
                            lbStatus.setText("Trống");
                            btnOpen.setVisible(true);
                            pnID.setVisible(false);
                        }
                    }
                });
            }
        } catch (SQLException ex) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        lbTieude = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JPBan = new javax.swing.JPanel();
        PanelOder = new javax.swing.JPanel();
        LbTenBan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnID = new javax.swing.JPanel();
        lbOrderID = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PanelBan = new javax.swing.JPanel();
        BtnAdd = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        btnHuy = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lbTongTien = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        PnBtn = new javax.swing.JPanel();
        btnOpen = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Jmenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý bán hàng");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setLocation(new java.awt.Point(0, 0));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lbTieude.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTieude.setForeground(new java.awt.Color(0, 153, 0));
        lbTieude.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTieude.setText("Bán hàng");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JPBan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách bàn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(51, 153, 255))); // NOI18N
        JPBan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JPBan.setPreferredSize(new java.awt.Dimension(200, 1000));
        JPBan.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jScrollPane1.setViewportView(JPBan);

        PanelOder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 3));
        PanelOder.setAutoscrolls(true);
        PanelOder.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LbTenBan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LbTenBan.setForeground(new java.awt.Color(153, 51, 0));
        LbTenBan.setText("Bàn 10");

        jLabel7.setForeground(new java.awt.Color(153, 51, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mug-icon .png"))); // NOI18N

        lbOrderID.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbOrderID.setForeground(new java.awt.Color(153, 51, 0));
        lbOrderID.setText("jLabel9");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 51, 0));
        jLabel8.setText("Mã hoá đơn");

        PanelBan.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách sản phẩm"));
        PanelBan.setEnabled(false);

        BtnAdd.setBackground(new java.awt.Color(153, 51, 0));
        BtnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnAdd.setForeground(new java.awt.Color(255, 255, 255));
        BtnAdd.setText("Thêm món");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        btnPay.setBackground(new java.awt.Color(0, 153, 0));
        btnPay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("Thanh toán");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        tblOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sản phẩm", "Số lượng", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrder.setToolTipText("");
        tblOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblOrder.setFocusable(false);
        tblOrder.setGridColor(new java.awt.Color(255, 255, 255));
        tblOrder.setName(""); // NOI18N
        tblOrder.setSelectionBackground(new java.awt.Color(102, 102, 255));
        tblOrder.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblOrder.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblOrder.setShowGrid(false);
        tblOrder.getTableHeader().setReorderingAllowed(false);
        tblOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrderMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblOrder);

        btnHuy.setBackground(new java.awt.Color(153, 51, 0));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Huỷ món");
        btnHuy.setEnabled(false);
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Tổng tiền :");

        lbTongTien.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbTongTien.setForeground(new java.awt.Color(255, 0, 0));
        lbTongTien.setText("jLabel10");

        jButton4.setBackground(new java.awt.Color(153, 51, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Huỷ bàn");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBanLayout = new javax.swing.GroupLayout(PanelBan);
        PanelBan.setLayout(PanelBanLayout);
        PanelBanLayout.setHorizontalGroup(
            PanelBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBanLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTongTien))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBanLayout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPay))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBanLayout.createSequentialGroup()
                        .addComponent(BtnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnHuy)))
                .addGap(18, 18, 18))
        );
        PanelBanLayout.setVerticalGroup(
            PanelBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBanLayout.createSequentialGroup()
                .addGroup(PanelBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(PanelBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbTongTien))
                .addGap(18, 18, 18)
                .addGroup(PanelBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout pnIDLayout = new javax.swing.GroupLayout(pnID);
        pnID.setLayout(pnIDLayout);
        pnIDLayout.setHorizontalGroup(
            pnIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnIDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnIDLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(lbOrderID)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(PanelBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnIDLayout.setVerticalGroup(
            pnIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnIDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbOrderID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(PanelBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 0));
        jLabel6.setText("Trạng thái: ");

        lbStatus.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbStatus.setForeground(new java.awt.Color(153, 51, 0));
        lbStatus.setText("abcccc");

        btnOpen.setBackground(new java.awt.Color(153, 255, 255));
        btnOpen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnOpen.setForeground(new java.awt.Color(204, 102, 0));
        btnOpen.setText("Đặt bàn");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        PnBtn.add(btnOpen);

        javax.swing.GroupLayout PanelOderLayout = new javax.swing.GroupLayout(PanelOder);
        PanelOder.setLayout(PanelOderLayout);
        PanelOderLayout.setHorizontalGroup(
            PanelOderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelOderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOderLayout.createSequentialGroup()
                        .addComponent(PnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOderLayout.createSequentialGroup()
                        .addComponent(pnID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
            .addGroup(PanelOderLayout.createSequentialGroup()
                .addGroup(PanelOderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOderLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lbStatus))
                    .addGroup(PanelOderLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel7)
                        .addGap(29, 29, 29)
                        .addComponent(LbTenBan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelOderLayout.setVerticalGroup(
            PanelOderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelOderLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(LbTenBan)))
                .addGap(31, 31, 31)
                .addGroup(PanelOderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStatus)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(pnID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setBackground(new java.awt.Color(153, 51, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 204, 0));
        jButton3.setText("Khách mang đi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Có người");

        jLabel2.setText("Bàn trống");

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Trạng thái ");

        Jmenu.setBackground(new java.awt.Color(153, 153, 255));
        Jmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/User-icon.png"))); // NOI18N
        Jmenu.setText("Tài khoản");
        Jmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JmenuMouseClicked(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Info-icon.png"))); // NOI18N
        jMenuItem1.setText("Thông tin cá nhân");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Jmenu.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/change-password-icon.png"))); // NOI18N
        jMenuItem2.setText("Đổi mật khẩu");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Jmenu.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logout-icon.png"))); // NOI18N
        jMenuItem3.setText("Đăng xuất");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Jmenu.add(jMenuItem3);

        jMenuBar1.add(Jmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jButton3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lbTieude)
                        .addContainerGap(419, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelOder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton3)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(20, 20, 20)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTieude, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelOder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new MyInfo(user).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JmenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JmenuMouseClicked

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked

    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new PasswordChange(user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new LoginForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn mở bàn ", "WARNING", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            String sql = "INSERT INTO orderr(TableID) VALUES (?)";
            try {
                PreparedStatement prest = db.connect().prepareStatement(sql);
                prest.setString(1, btnOpen.getName());
                if (prest.executeUpdate() > 0) {
                    db.UpdateSttTable("Có người", btnOpen.getName());
                    JPBan.removeAll();
                    ShowBan();
                    JPBan.updateUI();
                    JOptionPane.showMessageDialog(null, "Mở bàn thành công");
                    UpdateStatus(btnOpen.getName());
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Thất bại");
            }
        }
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        try {
            // TODO add your handling code here:
            ArrayList<Product> listPro = new ArrayList<>();
            ResultSet rs = db.getOrderDetails(Integer.parseInt(lbOrderID.getText()));
            while (rs.next()) {
                Product pro = new Product(rs.getString("IdProduct"), rs.getString("ProductName"), rs.getInt("Price"));
                listPro.add(pro);
            }

            int i = tblOrder.getSelectedRow();
            int res = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn huỷ món", "WARNING", JOptionPane.YES_NO_OPTION);
            if (res == JOptionPane.YES_OPTION) {
                String sql = "Delete from orderdetails where IdOrder = ? AND IdProduct = ?";
                PreparedStatement st;
                st = conn.prepareStatement(sql);
                st.setInt(1, Integer.parseInt(lbOrderID.getText()));
                st.setString(2, (listPro.get(i).getID()));
                if (st.executeUpdate() > 0) {
                    btnHuy.setEnabled(false);
                    JOptionPane.showMessageDialog(this, "Huỷ món thành công");
                    ShowOrderTotable(tblOrder, db.getOrderDetails(Integer.valueOf(lbOrderID.getText())));
                    lbTongTien.setText(String.valueOf(db.getTotalMoney(db.getOrderDetails(Integer.parseInt(lbOrderID.getText()))))+" VND");
                } else {
                    JOptionPane.showMessageDialog(null, "Huỷ món thất bại");
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Đã xảy ra lỗi");
        }
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
        int idOrder = Integer.valueOf(lbOrderID.getText());
        new PayForm(user, idOrder, btnOpen.getName()).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPayActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        // TODO add your handling code here:
        new OderProduct((Integer.valueOf(lbOrderID.getText()))).setVisible(true);
    }//GEN-LAST:event_BtnAddActionPerformed

    private void tblOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrderMouseClicked
        // TODO add your handling code here:
        btnHuy.setEnabled(true);
    }//GEN-LAST:event_tblOrderMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT IDOrder FROM orderr where TableID IS NULL AND Status = 0";
        try {
            Statement statement = conn.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            if (!rs.isBeforeFirst()) {
                String sql1 = "INSERT INTO orderr VALUES ()";
                PreparedStatement prest = db.connect().prepareStatement(sql1);
                prest.executeUpdate();
            } else {
                while (rs.next()) {
                    PanelOder.setVisible(true);
                    lbOrderID.setText(rs.getString("IDOrder"));
                    LbTenBan.setText("");
                    btnOpen.setName("NULL");
                    btnOpen.setVisible(false);
                    jLabel6.setVisible(false);
                    pnID.setVisible(true);
                    lbStatus.setVisible(false);
                    PanelBan.setVisible(true);
                    ShowOrderTotable(tblOrder, db.getOrderDetails(Integer.valueOf(lbOrderID.getText())));
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Đã xảy ra lỗi");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn huỷ bàn", "WARNING", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            if (tblOrder.getRowCount() == 0) {
                String sql = "Delete from orderr where IdOrder = ?";
                PreparedStatement st;
                try {
                    st = conn.prepareStatement(sql);
                    st.setInt(1, Integer.parseInt(lbOrderID.getText()));
                    if (st.executeUpdate() > 0) {
                        db.UpdateSttTable("Trống", btnOpen.getName());
                        JPBan.removeAll();
                        JPBan.updateUI();
                        ShowBan();
                        JOptionPane.showMessageDialog(this, "Huỷ bàn thành công");
                        PanelOder.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Huỷ bàn thất bại");
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Đã xảy ra lỗi");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Không thể huỷ bàn");
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(user.getRole().equals("admin")){
            this.dispose();
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JPanel JPBan;
    private javax.swing.JMenu Jmenu;
    private javax.swing.JLabel LbTenBan;
    private javax.swing.JPanel PanelBan;
    private javax.swing.JPanel PanelOder;
    private javax.swing.JPanel PnBtn;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel lbOrderID;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbTieude;
    public static javax.swing.JLabel lbTongTien;
    private javax.swing.JPanel pnID;
    public static javax.swing.JTable tblOrder;
    // End of variables declaration//GEN-END:variables
}
