/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectcafe;

import ConnectDb.dbconnect;
import Class.*;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.io.*;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class PayForm extends javax.swing.JFrame {

    User user;
    Integer IdOrder;
    String tblID;
    dbconnect db = new dbconnect();

    /**
     * Creates new form PayForm
     */
    java.sql.Date date = new java.sql.Date(new java.util.Date().getTime());

    public PayForm(User u, Integer id, String tableID) {
        this.user = u;
        this.tblID = tableID;
        this.IdOrder = id;
        initComponents();
        pnCusInfo.setVisible(false);
        MainForm.ShowOrderTotable(tblOrderDetails, db.getOrderDetails(IdOrder));
        lbtong.setText(String.valueOf(db.getTotalMoney(db.getOrderDetails(IdOrder))));
    }

    private void PrintBill() throws IOException {
        SimpleDateFormat dfm = new SimpleDateFormat("dd-MM-yyyy");
        String Billfile = "src/Bill/hd" + IdOrder + ".txt";
        File file = new File(Billfile);
        file.createNewFile();
        FileWriter mFileWriter = new FileWriter(Billfile);
        mFileWriter.write("\t\t\t\t\t\t\t THE COFFEE\n");
        mFileWriter.write("\t\t\t\t\t\t Địa chỉ: 22 Khâm Thiên,Đống Đa hà nội\n");
        mFileWriter.write("\t\t\t\t\t\t     SĐT: 0354508903\n");
        mFileWriter.write("\t\t\t\t\t\t ------------------\n");
        mFileWriter.write("\t\t\t\t\t\t HOÁ ĐƠN THANH TOÁN\n");
        mFileWriter.write("Mã hoá đơn: " + IdOrder + "\n");
        mFileWriter.write("Ngày: " + dfm.format(date) + "\n");
        mFileWriter.write("Nhân viên: " + user.getName() + "\n");
        if (pnCusInfo.isVisible()) {
            mFileWriter.write("Khách hàng: " + lbName.getText() + "\n");
        } else {
        }
        mFileWriter.write("-------------------------------------------------------------------\n");
        mFileWriter.write("Tên hàng \t\t\t" + "Số lượng \t\t\t" + "Đơn giá\n");
        for (int i = 0; i < tblOrderDetails.getRowCount(); i++) {
            mFileWriter.write(tblOrderDetails.getValueAt(i, 0) + " \t\t\t"+ tblOrderDetails.getValueAt(i, 1) + " \t\t\t\t" + tblOrderDetails.getValueAt(i, 2) + "\n");
        }
        mFileWriter.write("-------------------------------------------------------------------\n");
        mFileWriter.write("Tổng tiền \t\t\t\t" + lbtong.getText() + "\n");
        mFileWriter.write("Tiền khách đưa \t\t\t\t" + tfMoney.getText() + "\n");
        if (tfPoints.getText().equals("")) {
            mFileWriter.write("Giảm giá \t\t\t\t 0\n");
        } else {
            mFileWriter.write("Tiền khách đưa \t\t\t\t" + tfPoints.getText() + "\n");
        }
        mFileWriter.write("Hoàn tiền \t\t\t\t" + tfrefunds.getText() + "\n");
        mFileWriter.close();
        Desktop desktop = Desktop.getDesktop();
        if (file.exists()) {
            desktop.open(file);
        }
    }

    //Hàm tinh tiền cần trả lại
    private void moneytoreturn() {
        if (tfMoney.getText().length() > 0 && tfMoney.getText().length() < 10) {
            int Point;
            int SumMoney = Integer.valueOf(lbtong.getText());
            int Money = Integer.valueOf(tfMoney.getText());
            if (tfPoints.getText().length() == 0) {
                Point = 0;
            } else {
                Point = Integer.valueOf(tfPoints.getText());
            }
            if (tfMoney.getText().length() > 0 && Money > SumMoney) {
                tfrefunds.setText(String.valueOf(Money - SumMoney + Point) + " " + "VND");
            } else {
                tfrefunds.setText("");
            }
        } else {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderDetails = new javax.swing.JTable();
        pnCusInfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbId = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbPoint = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbDay = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lbtong = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        tfPoints = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfMoney = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfrefunds = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        lbNoti1 = new javax.swing.JLabel();
        lbNoti2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thanh toán");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Thanh toán");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(279, 279, 279))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tblOrderDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên sản phẩm", "Số lượng", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrderDetails);

        pnCusInfo.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Tên khách hàng:");

        lbName.setForeground(new java.awt.Color(255, 51, 51));
        lbName.setText("jLabel3");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Thông tin khách hàng ");

        lbId.setForeground(new java.awt.Color(255, 51, 51));
        lbId.setText("jLabel7");

        jLabel8.setText("Mã khách hàng:");

        jLabel9.setText("Điểm tích luỹ:");

        lbPoint.setForeground(new java.awt.Color(255, 51, 51));
        lbPoint.setText("jLabel10");

        jLabel11.setText("Này đăng kí:");

        lbDay.setForeground(new java.awt.Color(255, 51, 51));
        lbDay.setText("jLabel12");

        javax.swing.GroupLayout pnCusInfoLayout = new javax.swing.GroupLayout(pnCusInfo);
        pnCusInfo.setLayout(pnCusInfoLayout);
        pnCusInfoLayout.setHorizontalGroup(
            pnCusInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCusInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCusInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(pnCusInfoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(lbId))
                    .addGroup(pnCusInfoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(32, 32, 32)
                        .addComponent(lbPoint))
                    .addGroup(pnCusInfoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lbName))
                    .addGroup(pnCusInfoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(39, 39, 39)
                        .addComponent(lbDay)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        pnCusInfoLayout.setVerticalGroup(
            pnCusInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCusInfoLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addGroup(pnCusInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbId)
                    .addComponent(jLabel8))
                .addGap(27, 27, 27)
                .addGroup(pnCusInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbName)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(pnCusInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lbDay))
                .addGap(27, 27, 27)
                .addGroup(pnCusInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbPoint))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jButton3.setBackground(new java.awt.Color(0, 153, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 0));
        jButton3.setText("Lấy thông tin khách hàng");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("Danh sách sản phẩm đã gọi");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("Tổng tiền: ");

        lbtong.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbtong.setText("aassa");

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 51, 51));
        jCheckBox1.setText("Dùng điểm tích luỹ:");
        jCheckBox1.setToolTipText("");
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCheckBox1.setEnabled(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        tfPoints.setBackground(new java.awt.Color(204, 204, 204));
        tfPoints.setEnabled(false);
        tfPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPointsActionPerformed(evt);
            }
        });
        tfPoints.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPointsKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPointsKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Tiền khách đưa:");

        tfMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMoneyActionPerformed(evt);
            }
        });
        tfMoney.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMoneyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfMoneyKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setText("Tiền cần trả lại:");

        tfrefunds.setToolTipText("");

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Lưu hoá đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("VND");

        lbNoti1.setForeground(new java.awt.Color(255, 51, 51));

        lbNoti2.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfrefunds)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbtong)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel17))
                                .addComponent(lbNoti1)
                                .addComponent(tfMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbNoti2)))
                        .addGap(0, 46, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtong)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(tfPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(lbNoti1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNoti2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfrefunds))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnCusInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnCusInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean check;
        int SumMoney = Integer.parseInt(lbtong.getText());
        String sql = " Update orderr SET DateOrder = '" + date + "',Status = 1, EmpID = '" + user.getUserName() + "' "
                + ",Cusid = ?,Points = ? ,Total = " + SumMoney + " WHERE IDOrder = " + IdOrder + " ";
        try {
            PreparedStatement pres = db.connect().prepareStatement(sql);
            if(Integer.valueOf(tfMoney.getText()) < Integer.valueOf(lbtong.getText())){
                JOptionPane.showMessageDialog(null, "Tiền khách đưa phải lớn hơn số tiền phải trả");
                check = false;
            } else if (!pnCusInfo.isVisible()) {
                pres.setNull(1, 0);
                pres.setString(2, "0");
                check = true;
            } else if (tfPoints.getText().equals("")) {
                pres.setString(1, lbId.getText());
                pres.setString(2, "0");
                check = true;
            } else {
                if (Integer.parseInt(tfPoints.getText()) > Integer.parseInt(lbPoint.getText())) {
                    JOptionPane.showMessageDialog(null, "Điểm tích luỹ sử dụng không được lơn hơn điểm đang sở hữu");
                    check = false;
                } else {
                    pres.setString(1, lbId.getText());
                    pres.setString(2, tfPoints.getText());
                    check = true;
                }
            }
            if (check) {
                if (pres.executeUpdate() > 0) {
                    db.UpdateSttTable("Trống", tblID);
                    JOptionPane.showMessageDialog(this, "Thanh toán thành công");
                    new MainForm(user).ShowBan();
                    new MainForm(user).setVisible(true);
                    PrintBill();
                    this.setVisible(false);
                }
            }
        } catch (SQLException ex) {
            System.err.println(ex);
        } catch (IOException ex) {
            System.err.println(ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            tfPoints.setEnabled(true);
            tfPoints.setBackground(Color.WHITE);
        } else {
            tfPoints.setEnabled(false);
            tfPoints.setBackground(new Color(204, 204, 204));
            tfPoints.setText("");
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new CustommerManager(IdOrder, user, tblID).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMoneyActionPerformed

    private void tfMoneyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMoneyKeyPressed
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if (Character.isDigit(a)|| Character.isISOControl(a)) {
            tfMoney.setEditable(true);
            lbNoti2.setText("");
        } else {
            tfMoney.setEditable(false);
            lbNoti2.setText("Vui lòng nhập số");
        }
    }//GEN-LAST:event_tfMoneyKeyPressed

    private void tfMoneyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMoneyKeyReleased
        // TODO add your handling code here:
        moneytoreturn();
    }//GEN-LAST:event_tfMoneyKeyReleased

    private void tfPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPointsActionPerformed

    private void tfPointsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPointsKeyReleased
        // TODO add your handling code here:
        moneytoreturn();
    }//GEN-LAST:event_tfPointsKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        new MainForm(user).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void tfPointsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPointsKeyPressed
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if (Character.isDigit(a)|| Character.isISOControl(a)) {
            tfPoints.setEditable(true);
            lbNoti1.setText("");
        } else {
            tfPoints.setEditable(false);
            lbNoti1.setText("Vui lòng nhập số");
        }
    }//GEN-LAST:event_tfPointsKeyPressed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    public javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbDay;
    public javax.swing.JLabel lbId;
    public javax.swing.JLabel lbName;
    private javax.swing.JLabel lbNoti1;
    private javax.swing.JLabel lbNoti2;
    public javax.swing.JLabel lbPoint;
    private javax.swing.JLabel lbtong;
    public javax.swing.JPanel pnCusInfo;
    private javax.swing.JTable tblOrderDetails;
    private javax.swing.JTextField tfMoney;
    private javax.swing.JTextField tfPoints;
    private javax.swing.JLabel tfrefunds;
    // End of variables declaration//GEN-END:variables
}
