/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectcafe;

import Class.*;
import ConnectDb.dbconnect;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ProductManager extends javax.swing.JFrame {

    dbconnect db = new dbconnect();
    Connection conn = db.connect();
//    private DefaultTableModel tableProductType = new DefaultTableModel();
//    private DefaultTableModel tableProduct = new DefaultTableModel();

    /**
     * Creates new form ProductManager
     */
    public ProductManager() {
        initComponents();
//        tblLoaiSp.setModel(tableProductType);
//        tblProduct.setModel(tableProduct);
        ShowData(db.ListProductType());
        showComboBox();
        ShowDataProduct(db.ListProduct());
    }

    private void showComboBox() {
        ArrayList<ProductType> ListProductType = db.ListProductType();
        cbbLoaiSP.removeAllItems();
        for (ProductType pro : ListProductType) {
            cbbLoaiSP.addItem(pro.getTypeName());
        }
    }

    private void ShowData(ArrayList<ProductType> ListProductType) {
        DefaultTableModel tableProductType = (DefaultTableModel) tblLoaiSp.getModel();
        try {
            tableProductType.setRowCount(0);
            for (ProductType pro : ListProductType) {
                String rows[] = new String[2];
                rows[0] = pro.getIDType(); // lấy dữ liệu tại cột số 1 (ứng với mã hàng)
                rows[1] = pro.getTypeName(); // lấy dữ liệu tai cột số 2 ứng với tên hàng
                tableProductType.addRow(rows); // đưa dòng dữ liệu vào tableModel để hiện thị lên jtable
            }
        } catch (Exception e) {
        }
        btnThem.setEnabled(true);
        btnXoa.setEnabled(false);
        BtnSua.setEnabled(false);
    }

    public void ShowDataProduct(ArrayList<Product> ListProduct) {
        DefaultTableModel tableProduct = (DefaultTableModel) tblProduct.getModel();
        tableProduct.setRowCount(0);
        for (Product pro : ListProduct) {
            String rows[] = new String[4];
            rows[0] = pro.getID();
            rows[1] = pro.getProductName();
            rows[2] = pro.getTypeName();
            String price = Integer.toString(pro.getPrice());
            rows[3] = price;
            tableProduct.addRow(rows); // đưa dòng dữ liệu vào tableModel để hiện thị lên jtable
        }
    }

    //Hàm để check xem nhập đủ thông tin chưa
    public boolean checkRong() {
        if (tfIdProductType.getText().equals("") || tfTenloai.getText().equals("")) {
            return true;
        } else {
            return false;
        }
    }
    // Hàm này để reset toàn bộ text trên textfield và combobox

    private void resetText() {
        tfIdProductType.setText("");
        tfTenloai.setText("");
        tfProductPrice.setText("");
        tfProductName.setText("");
        TfIdProduct.setText("");
        tfIdProductType.setEnabled(true);
        TfIdProduct.setEnabled(true);
        btnThemSP.setEnabled(true);
        btnXoaSP.setEnabled(false);
        BtnSuaSP.setEnabled(false);
        ShowData(db.ListProductType());
        showComboBox();
        ShowDataProduct(db.ListProduct());

    }

    // hàm check xem mã đã tồn tại chưa
    private boolean CheckidProductType() {
        int i = 0;
        boolean kt = true;
        while (i < tblLoaiSp.getRowCount()) {
            if (tfIdProductType.getText().equals((String) tblLoaiSp.getValueAt(i, 0))) {
                kt = false;
                break;
            } else {
                i++;
            }
        }
        return kt;
    }

    private boolean CheckidProduct() {
        int i = 0;
        boolean kt = true;
        while (i < tblProduct.getRowCount()) {
            if (TfIdProduct.getText().equals((String) tblProduct.getValueAt(i, 0))) {
                kt = false;
                break;
            } else {
                i++;
            }
        }
        return kt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        tfIdProductType = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        BtnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();
        lbName1 = new javax.swing.JLabel();
        tfTenloai = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoaiSp = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        jToolBar2 = new javax.swing.JToolBar();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfProductName = new javax.swing.JTextField();
        cbbLoaiSP = new javax.swing.JComboBox<>();
        tfProductPrice = new javax.swing.JTextField();
        btnThemSP = new javax.swing.JButton();
        BtnSuaSP = new javax.swing.JButton();
        BtnReset1 = new javax.swing.JButton();
        btnXoaSP = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        TfIdProduct = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfSearchPro = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý sản phẩm");
        setBackground(new java.awt.Color(102, 153, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setForeground(java.awt.Color.white);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jToolBar1.setRollover(true);

        lbName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbName.setForeground(new java.awt.Color(255, 0, 51));
        lbName.setText("Mã loại sản phẩm :");

        tfIdProductType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdProductTypeActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-icon.png"))); // NOI18N
        btnThem.setText("  Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        BtnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-wand-icon.png"))); // NOI18N
        BtnSua.setText("   Sửa");
        BtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete-icon.png"))); // NOI18N
        btnXoa.setText("   Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        BtnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh-icon.png"))); // NOI18N
        BtnReset.setText("  Làm mới");
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        lbName1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbName1.setForeground(new java.awt.Color(255, 0, 51));
        lbName1.setText("Tên loại sản phẩm :");

        tfTenloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenloaiActionPerformed(evt);
            }
        });

        tblLoaiSp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã loại sản phẩm", "Tên loại sản phẩm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLoaiSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiSpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLoaiSp);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
        );

        jLabel5.setText("Tìm kiếm:");

        tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnThem)
                        .addGap(40, 40, 40)
                        .addComponent(BtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(BtnReset)
                        .addGap(27, 27, 27))
                    .addComponent(lbName1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(42, 42, 42))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfIdProductType, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(tfTenloai)
                            .addComponent(tfSearch))
                        .addGap(81, 81, 81)))
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdProductType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName1)
                    .addComponent(tfTenloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnReset)
                    .addComponent(btnXoa)
                    .addComponent(BtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem))
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jToolBar1.add(jPanel1);

        jTabbedPane1.addTab("Loại sản phẩm", jToolBar1);

        jToolBar2.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Tên sản phẩm");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Loại sản phẩm");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Giá sản phẩm");

        tfProductPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfProductPriceKeyPressed(evt);
            }
        });

        btnThemSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-icon.png"))); // NOI18N
        btnThemSP.setText("  Thêm");
        btnThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPActionPerformed(evt);
            }
        });

        BtnSuaSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-wand-icon.png"))); // NOI18N
        BtnSuaSP.setText("   Sửa");
        BtnSuaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSuaSPActionPerformed(evt);
            }
        });

        BtnReset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh-icon.png"))); // NOI18N
        BtnReset1.setText("  Làm mới");
        BtnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReset1ActionPerformed(evt);
            }
        });

        btnXoaSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete-icon.png"))); // NOI18N
        btnXoaSP.setText("   Xoá");
        btnXoaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSPActionPerformed(evt);
            }
        });

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Loại sản phẩm", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProduct);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Mã sản phẩm");

        TfIdProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfIdProductActionPerformed(evt);
            }
        });

        jLabel6.setText("Tìm kiếm: ");

        tfSearchPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchProKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnThemSP))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfProductName, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                            .addComponent(TfIdProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                            .addComponent(cbbLoaiSP, 0, 300, Short.MAX_VALUE)
                                            .addComponent(tfProductPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                            .addComponent(tfSearchPro)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(BtnSuaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(btnXoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnReset1)
                                        .addGap(8, 8, 8)))))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(tfSearchPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(TfIdProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(tfProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(cbbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnSuaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoaSP)
                        .addComponent(BtnReset1))
                    .addComponent(btnThemSP))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jToolBar2.add(jPanel3);

        jTabbedPane1.addTab("Sản phẩm", jToolBar2);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Go-back-icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfTenloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenloaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenloaiActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        // TODO add your handling code here:
        resetText();
    }//GEN-LAST:event_BtnResetActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed

        int i = tblLoaiSp.getSelectedRow();
        int res = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xoá loại sản phẩm", "WARNING", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM `producttype` WHERE IDType = ?";
            String sql2 = "DELETE FROM `product` Where IdType = ?";
            PreparedStatement st, st2;
            try {
                st2 = conn.prepareStatement(sql2);
                st = conn.prepareStatement(sql);
                st2.setString(1, (String) tblLoaiSp.getValueAt(i, 0));
                st.setString(1, (String) tblLoaiSp.getValueAt(i, 0));
                if (st2.executeUpdate() > 0 && st.executeUpdate() > 0 || st.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(this, "Xoá thành công");
                    resetText();
                } else {
                    JOptionPane.showMessageDialog(null, "Xoá không thành công");
                }
            } catch (SQLException ex) {
                System.err.println(ex);

            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void BtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSuaActionPerformed

        // TODO add your handling code here:
        String sql = "UPDATE producttype SET IDType = ?,TypeName = ? WHERE IDType = ?";
        int i = tblLoaiSp.getSelectedRow();
        if (checkRong()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        } else if (CheckidProductType() || tfIdProductType.getText().equals(tblLoaiSp.getValueAt(i, 0))) {
            try {
                PreparedStatement pres = conn.prepareStatement(sql);
                pres.setString(1, tfIdProductType.getText());
                pres.setString(2, tfTenloai.getText());
                pres.setString(3, (String) tblLoaiSp.getValueAt(i, 0));
                if (pres.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(this, "Sửa thành công");
                    resetText();

                }
            } catch (SQLException ex) {
                System.err.println(ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Mã loại sản phẩm đã tồn tại", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        if (checkRong()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }
        if (!CheckidProductType()) {
            JOptionPane.showMessageDialog(this, "Mã loại sản phẩm đã tồn tại", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String sql = "INSERT INTO producttype(IDType,TypeName) VALUES ('" + tfIdProductType.getText() + "','" + tfTenloai.getText() + "')";
                PreparedStatement prest = conn.prepareStatement(sql);
                if (prest.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "Thêm loại sản phẩm thành công.");
                    resetText();
                } else {
                    JOptionPane.showMessageDialog(null, "Thêm loại sản phẩm thất bại.");
                }

            } catch (Exception e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void tfIdProductTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdProductTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdProductTypeActionPerformed

    private void tblLoaiSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiSpMouseClicked
        // TODO add your handling code here:
        int i = tblLoaiSp.getSelectedRow();
        tfIdProductType.setText((String) tblLoaiSp.getValueAt(i, 0));
        tfTenloai.setText((String) tblLoaiSp.getValueAt(i, 1));
        btnThem.setEnabled(false);
        BtnSua.setEnabled(true);
        btnXoa.setEnabled(true);
    }//GEN-LAST:event_tblLoaiSpMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_formMouseClicked

    private void btnThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPActionPerformed
        // TODO add your handling code here:
        if (tfProductName.getText().equals("") || tfProductPrice.getText().equals("") || TfIdProduct.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        } else if (!CheckidProduct()) {
            JOptionPane.showMessageDialog(null, "Mã sản phẩm đã tồn tại");
        } else {
            try {
                String sql = "INSERT INTO product VALUES (?,?,?,?)";
                PreparedStatement prest = conn.prepareStatement(sql);
                prest.setString(1, TfIdProduct.getText());
                prest.setString(2, tfProductName.getText());
                ArrayList<ProductType> st = db.ListProductType();

                ProductType productType = st.get(cbbLoaiSP.getSelectedIndex());
                String id = productType.getIDType();
                prest.setString(3, id);
                prest.setInt(4, Integer.parseInt(tfProductPrice.getText()));
                if (prest.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "Thêm sản phẩm thành công.");
                    resetText();
                } else {
                    JOptionPane.showMessageDialog(null, "Thêm sản phẩm thất bại.");
                }
            } catch (Exception e) {
            }
        }

    }//GEN-LAST:event_btnThemSPActionPerformed

    private void BtnSuaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSuaSPActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE product SET IdProduct = ?,ProductName = ?, IdType = ?, Price = ? WHERE IdProduct = ?";
        int i = tblProduct.getSelectedRow();
        if (TfIdProduct.getText().equals("") || tfProductName.getText().equals("") || tfProductPrice.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }
        if (CheckidProduct() || TfIdProduct.getText().equals(tblProduct.getValueAt(i, 0))) {
            try {
                PreparedStatement pres = conn.prepareStatement(sql);
                pres.setString(1, TfIdProduct.getText());
                pres.setString(2, tfProductName.getText());
                ArrayList<ProductType> pro = db.ListProductType();
                ProductType productType = pro.get(cbbLoaiSP.getSelectedIndex());
                String id = productType.getIDType();
                pres.setString(3, id);
                try {
                    pres.setInt(4, Integer.parseInt(tfProductPrice.getText()));
                } catch (NumberFormatException w) {
                    JOptionPane.showMessageDialog(null, "Giá phải là số");
                }
                pres.setString(5, (String) tblProduct.getValueAt(i, 0));
                if (pres.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(this, "Sửa thành công");
                    resetText();
                }
            } catch (SQLException ex) {
                System.err.println(ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Mã sản phẩm đã tồn tại", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnSuaSPActionPerformed

    private void BtnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReset1ActionPerformed
        // TODO add your handling code here:
        resetText();
    }//GEN-LAST:event_BtnReset1ActionPerformed

    private void btnXoaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSPActionPerformed
        // TODO add your handling code here:
        int i = tblProduct.getSelectedRow();
        int res = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn thoát tài khoản", "WARNING", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM product WHERE IdProduct = ?";
            PreparedStatement st;
            try {
                st = conn.prepareStatement(sql);
                st.setString(1, (String) tblProduct.getValueAt(i, 0));
                if (st.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(this, "Xoá thành công");
                    resetText();
                }
            } catch (SQLException ex) {
                System.err.println(ex);

            }
        }
    }//GEN-LAST:event_btnXoaSPActionPerformed

    private void TfIdProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfIdProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfIdProductActionPerformed

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
        // TODO add your handling code here:
        int i = tblProduct.getSelectedRow();
        TfIdProduct.setText((String) tblProduct.getValueAt(i, 0));
        tfProductName.setText((String) tblProduct.getValueAt(i, 1));
        cbbLoaiSP.setSelectedItem(tblProduct.getValueAt(i, 2));
        tfProductPrice.setText((String) tblProduct.getValueAt(i, 3));
        btnThem.setEnabled(false);
        BtnSuaSP.setEnabled(true);
        btnXoaSP.setEnabled(true);
    }//GEN-LAST:event_tblProductMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyReleased
        // TODO add your handling code here:
        ShowData(db.SearchProductType(tfSearch.getText()));
    }//GEN-LAST:event_tfSearchKeyReleased

    private void tfSearchProKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchProKeyReleased
        // TODO add your handling code here:
        ShowDataProduct(db.SearchProduct(tfSearchPro.getText()));
    }//GEN-LAST:event_tfSearchProKeyReleased

    private void tfProductPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfProductPriceKeyPressed
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if (Character.isDigit(a)|| Character.isISOControl(a)) {
            tfProductPrice.setEditable(true);
        } else {
            tfProductPrice.setEditable(false);
        }
    }//GEN-LAST:event_tfProductPriceKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnReset;
    private javax.swing.JButton BtnReset1;
    private javax.swing.JButton BtnSua;
    private javax.swing.JButton BtnSuaSP;
    private javax.swing.JTextField TfIdProduct;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemSP;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaSP;
    private javax.swing.JComboBox<String> cbbLoaiSP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbName1;
    private javax.swing.JTable tblLoaiSp;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField tfIdProductType;
    private javax.swing.JTextField tfProductName;
    private javax.swing.JTextField tfProductPrice;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfSearchPro;
    private javax.swing.JTextField tfTenloai;
    // End of variables declaration//GEN-END:variables
}
